### ISSUE TITLE
prevent quest points spawning at same location

### ISSUE THREAD

**Issue by nioncode** [SarenCurrie/street-quest#33]
Otherwise, they can't be interacted with.

**Comment by franomai** [comment]
Offsets should resolve this, plus some improvements to the randomness were added. However, this is only a temporary fix.

**Comment by nioncode** [comment]
Still happens sometimes for quest starting points, if they get snapped back to the same street address.
